language: node_js

node_js:
  - 'node'
  - 'lts/*'

addons:
    code_climate:
        repo_token: 44a25306ec1296a0091caa2abffabc806367a67c62c7337923ccdb3dd43ef979

script:
  - npm run test:coverage
  - CI=false npm build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
  - npm install codeclimate-test-reporter istanbul -g

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules